module.exports = {
    "languages":[
        {
            "name":"Android",
            "image":"/icons/android.svg"
        },
        {
            "name": "Arduino",
            "image": "/icons/arduino.svg"
        },
        {
            "name":"Bootstrap",
            "image":"/icons/bootstrap.svg"
        },
        {
            "name":"C#",
            "image":"/icons/csharp.svg"
        },
        {
            "name":"CSS3",
            "image":"/icons/css3.svg"
        },
        {
            "name":"Daisyui",
            "image":"/icons/daisyui.svg"
        },
        {
            "name":"ExpressJS",
            "image":"/icons/expressjs.svg"
        },
        {
            "name":"Fastify",
            "image":"/icons/fastify.svg"
        },
        {
            "name":"Figma",
            "image":"/icons/figma.svg"
        },
        {
            "name":"Git",
            "image":"/icons/git.svg"
        },
        {
            "name":"Github",
            "image":"/icons/github.svg"
        },
        {
            "name":"Golang",
            "image":"/icons/golang.svg"
        },
        {
            "name":"HTML5",
            "image":"/icons/html5.svg"
        },
        {
            "name":"JavaScript",
            "image":"/icons/javascript.svg"
        },
        {
            "name":"Jenkins",
            "image":"/icons/jenkins.svg"
        },
        {
            "name":"Linux",
            "image":"/icons/linux.svg"
        },
        {
            "name":"MongoDB",
            "image":"/icons/mongodb.svg"
        },
        {
            "name":"NextJS",
            "image":"/icons/nextjs.svg"
        },
        {
            "name":"NodeJS",
            "image":"/icons/nodejs.svg"
        },
        {
            "name":"PHP",
            "image":"/icons/php.svg"
        },
        {
            "name":"Python",
            "image":"/icons/python.svg"
        },
        {
            "name":"React Native",
            "image":"/icons/react-native.svg"
        },
        {
            "name":"SASS",
            "image":"/icons/sass.svg"
        },
        {
            "name":"Svelte",
            "image":"/icons/svelte.svg"
        },
        {
            "name":"TailwindCSS",
            "image":"/icons/tailwindcss.svg"
        },
        {
            "name":"Typescript",
            "image":"/icons/typescript.svg"
        },
        {
            "name":"Unity",
            "image":"/icons/unity.svg"
        },
        {
            "name":"Vercel",
            "image":"/icons/vercel.svg"
        },
        {
            "name":"Vue",
            "image":"/icons/vue.svg"
        },
        {
            "name":"Yarn",
            "image":"/icons/yarn.svg"
        }
    ],
    "projects":[
        {
            "name":"AnimesWatch",
            "thumb":"https://i.imgur.com/vAhklkx.gif",
            "desc":"A website where you can watch anime with Turkish subtitles without interruption and freezing.",
            "link":"https://animeswatch.com"
        },
        {
            "name":"Saely",
            "thumb":"https://i.imgur.com/9rOYU1h.gif",
            "desc":"Anime news site where you can follow the latest anime news quickly",
            "link":"https://saely.me"
        }
    ]
}